### ISSUE TITLE
Example not working in Safari (Mavericks)

### ISSUE THREAD

**Issue by kounips** [makinacorpus/Leaflet.MeasureControl#10]
Hi,
I can't draw a line in the example in my Safari browser.
Any prior compatibility issue?

**Comment by neothemachine** [comment]
Demo not working for me, Firefox. It's because github pages are https and you load leaflet from http which is now forbidden.

**Comment by fredericbonifas** [comment]
I just tried with Firefox 38.0 on Ubuntu 14.04 and the demo is working fine. What is the config for which you have problems ?

**Comment by neothemachine** [comment]
Sorry, only happens when I access it via https:// (I use HTTPS Everywhere which does the switch automatically). So I guess it can be ignored for now.

**Comment by fredericbonifas** [comment]
The demo is working fine on Safari 9.1.1
I close this issue, please re-open it if you meet this problem again.
