### ISSUE TITLE
Can't finish drawing line over added layers

### ISSUE THREAD

**Issue by StepanKuzmin** [makinacorpus/Leaflet.MeasureControl#11]
Can't finish drawing line over added layers

![2014-12-29 13 17 48](https://cloud.githubusercontent.com/assets/533564/5567063/23a37190-8f5d-11e4-9058-22f0890a64fc.png)

**Comment by fredericbonifas** [comment]
Hi @StepanKuzmin,

Did you manage to fix this problem ?
If not, could you please setup a minimal jsfiddle reproducing this bug so we can have a look ?

**Comment by StepanKuzmin** [comment]
@fredericbonifas thanks for reply! I can't reproduce this bug right now. It seems to me, that it was problem with my project setup (I'm using leaflet and leaflet.draw from bower).

**Comment by tomchadwin** [comment]
I have something similar - measure tool clicks do not register is the clicks are on map features with bound popups: the click even reveals the popup, and the measure event does not take place. In addition, the measure cursor (crosshair) is only there when the pointer is not over a map feature. When over a map feature, even with measure activated, the cursor reverts to the pointing finger.
