### ISSUE TITLE
Small measure control icon, does not fit button

### ISSUE THREAD

**Issue by water42** [makinacorpus/Leaflet.MeasureControl#13]
https://imgur.com/VpHevYW

**Comment by fredericbonifas** [comment]
Thank you for reporting this bug @water42 .
I don't reproduce this bug, does it happen on this page too for you: http://makinacorpus.github.io/Leaflet.MeasureControl/ ?

If so, could you please provide more information, like which OS and browser you use ?

**Comment by water42** [comment]
Hi Frederic,

I'm currently getting this bug testing through the Chrome browser in an Ionic project. I am using the most updated version of leaflet-draw, but I also tested with version of leaflet-draw included with the package and it was still giving me the off center image. My repository where I am getting this bug is on github, I could give you info on how to test this if desired-- its quite straightforward: https://github.com/water42/TractNotes

The index.html in /www loads the scripts, and in /www/lib I believe I have all the correct leaflet-measure and leaflet-draw files within their folders.

Thanks

**Comment by water42** [comment]
Closing issue since I ended up implementing the measure function onto the default leaflet-draw line button.
