### ISSUE TITLE
Demo in HTTPs?

### ISSUE THREAD

**Issue by valerio-bozzolan** [makinacorpus/Leaflet.MeasureControl#31]
I noticed there are some small URL that can be fixed to have a demo supporting HTTPs:

https://makinacorpus.github.io/Leaflet.MeasureControl/

Is this known? :) Thank you so much!

**Comment by Bo-Duke** [comment]
Thanks for the heads-up! Indeed the demo was using leaflet's CDN which doesn't seem to support HTTPS.

Fixed with fa202ab
