### ISSUE TITLE
Enhancement - Embed MeasureControl to L.Draw

### ISSUE THREAD

**Issue by IslamHossam** [makinacorpus/Leaflet.MeasureControl#6]
Hello,

First, I thank all contributors for this valuable plugin.
Second, Can we embed Measure Control functionality to L.Control.Draw,
In Short, I need to draw my shapes "polygon & rectangle "by Leaflet.Draw plugin and show distance that calculated by Leaflet.MeasureControl, without adding MeasureControl control on the map.

Thanks,
Islam Hossam

**Comment by fredericbonifas** [comment]
Checking the Leaflet.Draw demo, it is now possible to display the distance while drawing a line: http://leaflet.github.io/Leaflet.draw/
